### PR TITLE
added download app section

### PR DESCRIPTION
**Pull request by rowhitswami**
Fixes issue #24 

Changes: decreased the code redundancy of sponsors sections.  Now the same block of code will serve for both desktop and mobile users.  Also added a 'Download App' section which can be used whenever the app is ready.

Screenshots for the change: 

**Sponsors Section**
Screenshot_from_2017_10_18_05_41_44

**Download App Section**
Screenshot_from_2017_10_18_05_41_50

**And here mobile view of both changes**
Screenshot_from_2017_10_18_05_42_10

### CODE REVIEW

**Comment by ashwini0529** [comment]
@rowhitswami You've *App Store* image in your commit. 
Please remove that.

**Review by ashwini0529 — CHANGES_REQUESTED** [review]
@rowhitswami Remove App Store image

**Review by ashwini0529 — CHANGES_REQUESTED** [review]
Can you please remove `npm-debug.log` ?

**Comment by rowhitswami** [comment]
@ashwini0529 Done :)

**Comment by ashwini0529** [comment]
Here you go @rowhitswami ! :)

**Comment by rowhitswami** [comment]
@ashwini0529 Thank you. Please let me know if you face any issue regarding design and layout in future. I'd love to do it.

**Comment by technophilic** [comment]
chrome_2017-10-19_18-14-54

image

@ashwini0529 this commit breaks the sponsors section of mobile layout. In fact it is even a little absurd for desktop layout in my opinion. What should be done?

**Comment by rowhitswami** [comment]
@ashwini0529 Please suggest any improvement

**Pull request merged**
