### PR TITLE
fix gramatical errors

### PR DESCRIPTION
**Pull request by sidkola**
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Demo Link: [Deploy the website somewhere(surge,github,etc) and put here the link of it]

Screenshots for the change: [Please add relevant Screenshots of the changes you made]

### CODE REVIEW

**Comment by abhinav-adtechs** [comment]
fix merge conflicts and pr again.

**Comment by ashwini0529** [comment]
@technophilic What's this!

**Comment by technophilic** [comment]
@ashwini0529 
This is the gh-pages branch. This branch contains the all the minified,unreadable code and compressed assets. This branch is not manually maintained and is automatically updated by the build script when hit with ```npm deploy```  , the commit message is the time-stamp of the deployment.

@sidkola 
All changes must be made to the files inside src folder of the *master* branch. Please PR again with changes , if they are still relevant. i will take care of deploying it :)

**Comment by ashwini0529** [comment]
Closing this PR.

**Pull request closed without merging**
