### PR TITLE
Added TechGIG as a Platform Sponsor in the Sponsor's section

### PR DESCRIPTION
**Pull request by logichub**
Fixes issue #7

**Changes**

- Made a sub-section named Platform Sponsor inside the Sponsors section and placed Techgig logo there

**Screenshots for the change**
image

### CODE REVIEW

**Comment by aalind0** [comment]
@logichub Please resolve conflicts ! Plus make sure this is fully responsive.

**Comment by logichub** [comment]
@aalind0 Issue was resolved. It must be responsive as I created this new sub-section similar to the sponsor section code.

**Comment by ashwini0529** [comment]
@logichub TechGig is also mentioned in sponsors list. Please remove the redundancy.

**Comment by logichub** [comment]
@ashwini0529 
It was already removed. See https://github.com/GDGVIT/Devfest-2.0/issues/7#issuecomment-336368420.

**Pull request merged**
